# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(300, 150)
        Form.setMinimumSize(QtCore.QSize(300, 150))
        Form.setMaximumSize(QtCore.QSize(300, 150))
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 10, 239, 112))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.Oil_1 = QtWidgets.QPushButton(self.layoutWidget)
        self.Oil_1.setObjectName("Oil_1")
        self.gridLayout.addWidget(self.Oil_1, 0, 0, 1, 1)
        self.Repair = QtWidgets.QPushButton(self.layoutWidget)
        self.Repair.setObjectName("Repair")
        self.gridLayout.addWidget(self.Repair, 0, 1, 1, 1)
        self.Case_1 = QtWidgets.QPushButton(self.layoutWidget)
        self.Case_1.setObjectName("Case_1")
        self.gridLayout.addWidget(self.Case_1, 0, 2, 1, 1)
        self.Oil_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.Oil_2.setObjectName("Oil_2")
        self.gridLayout.addWidget(self.Oil_2, 1, 0, 1, 1)
        self.Ammo = QtWidgets.QPushButton(self.layoutWidget)
        self.Ammo.setObjectName("Ammo")
        self.gridLayout.addWidget(self.Ammo, 1, 1, 1, 1)
        self.Case_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.Case_2.setObjectName("Case_2")
        self.gridLayout.addWidget(self.Case_2, 1, 2, 1, 1)
        self.Oil_3 = QtWidgets.QPushButton(self.layoutWidget)
        self.Oil_3.setObjectName("Oil_3")
        self.gridLayout.addWidget(self.Oil_3, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 1, 1, 1)
        self.Case_3 = QtWidgets.QPushButton(self.layoutWidget)
        self.Case_3.setObjectName("Case_3")
        self.gridLayout.addWidget(self.Case_3, 2, 2, 1, 1)
        self.Money_money_money = QtWidgets.QLineEdit(self.layoutWidget)
        self.Money_money_money.setEnabled(True)
        self.Money_money_money.setInputMask("")
        self.Money_money_money.setText("")
        self.Money_money_money.setMaxLength(3)
        self.Money_money_money.setObjectName("Money_money_money")
        self.gridLayout.addWidget(self.Money_money_money, 3, 0, 1, 2)
        self.Add_money = QtWidgets.QPushButton(self.layoutWidget)
        self.Add_money.setObjectName("Add_money")
        self.gridLayout.addWidget(self.Add_money, 3, 2, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Oil_1.setText(_translate("Form", "可乐"))
        self.Repair.setText(_translate("Form", "维修"))
        self.Case_1.setText(_translate("Form", "白箱"))
        self.Oil_2.setText(_translate("Form", "妹汁"))
        self.Ammo.setText(_translate("Form", "弹药"))
        self.Case_2.setText(_translate("Form", "蓝箱"))
        self.Oil_3.setText(_translate("Form", "炸虾"))
        self.label.setText(_translate("Form", "<          >"))
        self.Case_3.setText(_translate("Form", "紫箱"))
        self.Money_money_money.setPlaceholderText(_translate("Form", "输入物资数"))
        self.Add_money.setText(_translate("Form", "增加"))
